'use client';

import { Button } from '@/components/ui';
import { Printer, Landmark } from 'lucide-react';
import type { Donation } from '@/types';

interface DonationReceiptProps {
  donation: Donation;
  churchName?: string;
  logoUrl?: string | null;
  onClose: () => void;
}

function formatCurrency(amount: number): string {
  return `GHS ${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function receiptNumber(donation: Donation): string {
  return donation._id.slice(-8).toUpperCase();
}

interface ReceiptRow {
  label: string;
  value: string;
  emphasize?: boolean;
}

function buildRows(donation: Donation, donorName: string): ReceiptRow[] {
  const rows: ReceiptRow[] = [
    { label: 'Donor', value: donorName },
    { label: 'Date', value: formatDate(donation.donationDate) },
    { label: 'Amount', value: formatCurrency(donation.amount), emphasize: true },
    { label: 'Type', value: donation.offeringTypeId?.name || donation.donationType || 'General' },
    { label: 'Payment Method', value: donation.paymentMethod?.replace('_', ' ') || 'N/A' },
  ];
  if (donation.chequeNumber) rows.push({ label: 'Cheque No.', value: donation.chequeNumber });
  if (donation.paidForMonth) rows.push({ label: 'For Month', value: donation.paidForMonth });
  if (donation.fundBucketId) rows.push({ label: 'Fund', value: donation.fundBucketId.name });
  return rows;
}

// Print opens a bare, unstyled window (no Tailwind sheet available there), so
// its markup is built standalone with its own inline-styled, always-light
// letterhead - independent of the on-screen preview's theme-aware classes.
function buildPrintHtml(donation: Donation, churchName: string, logoUrl: string | null | undefined, rows: ReceiptRow[]): string {
  const rowsHtml = rows
    .map(
      (row) => `
        <tr>
          <td style="padding:10px 0;border-bottom:1px solid #eee;color:#666;width:40%;">${row.label}</td>
          <td style="padding:10px 0;border-bottom:1px solid #eee;font-weight:${row.emphasize ? 'bold' : '500'};font-size:${row.emphasize ? '18px' : '14px'};color:#111;">${row.value}</td>
        </tr>`
    )
    .join('');

  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="${churchName} logo" style="width:56px;height:56px;object-fit:contain;border-radius:8px;border:1px solid #eee;" />`
    : `<div style="width:56px;height:56px;border-radius:8px;background:#EEF2FF;color:#4F46E5;display:flex;align-items:center;justify-content:center;font-size:22px;font-weight:bold;">${churchName.charAt(0).toUpperCase()}</div>`;

  return `
    <html>
      <head>
        <title>Donation Receipt</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; max-width: 640px; margin: 0 auto; color: #111; }
          .letterhead { display: flex; align-items: center; gap: 16px; padding-bottom: 20px; border-bottom: 2px solid #4F46E5; }
          .letterhead h1 { font-size: 20px; margin: 0; color: #111; }
          .letterhead p { margin: 2px 0 0; color: #666; font-size: 13px; }
          .title { font-size: 22px; font-weight: bold; margin: 28px 0 4px; color: #111; }
          .receipt-no { color: #999; font-size: 12px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; color: #999; font-size: 12px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="letterhead">
          ${logoHtml}
          <div>
            <h1>${churchName}</h1>
            <p>Official Donation Receipt</p>
          </div>
        </div>
        <div class="title">Donation Receipt</div>
        <div class="receipt-no">Receipt No. ${receiptNumber(donation)}</div>
        <table>${rowsHtml}</table>
        <div class="footer">This receipt was generated by ${churchName} via Sanctuary Connect.</div>
        <script>window.print(); window.close();</script>
      </body>
    </html>
  `;
}

export default function DonationReceipt({ donation, churchName = 'Church', logoUrl, onClose }: DonationReceiptProps) {
  const donorName = donation.donorId
    ? `${donation.donorId.firstName} ${donation.donorId.lastName}`
    : donation.donorType === 'collective'
      ? (donation.donorName ? `Collective — ${donation.donorName}` : 'Collective Offering')
      : 'Anonymous';

  const rows = buildRows(donation, donorName);

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(buildPrintHtml(donation, churchName, logoUrl, rows));
    printWindow.document.close();
  };

  return (
    <div>
      {/* Letterhead */}
      <div className="flex items-center gap-4 pb-4 border-b-2 border-primary">
        {logoUrl ? (
          <img src={logoUrl} alt={`${churchName} logo`} className="w-14 h-14 object-contain rounded-lg border border-border flex-shrink-0" />
        ) : (
          <div className="w-14 h-14 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
            <Landmark className="w-7 h-7" />
          </div>
        )}
        <div className="min-w-0">
          <h2 className="text-base font-bold text-foreground truncate">{churchName}</h2>
          <p className="text-xs text-muted">Official Donation Receipt</p>
        </div>
      </div>

      <h1 className="text-xl font-bold text-foreground mt-6">Donation Receipt</h1>
      <p className="text-xs text-muted mb-6">Receipt No. {receiptNumber(donation)}</p>

      <table className="w-full">
        <tbody>
          {rows.map((row) => (
            <tr key={row.label} className="border-b border-border">
              <td className="py-2.5 text-sm text-muted w-2/5">{row.label}</td>
              <td className={`py-2.5 text-foreground ${row.emphasize ? 'text-lg font-bold' : 'text-sm font-medium'}`}>
                {row.value}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="text-xs text-muted mt-6 pt-4 border-t border-border">
        This receipt was generated by {churchName} via Sanctuary Connect.
      </p>

      <div className="flex justify-end gap-3 pt-4 mt-2">
        <Button variant="outline" onClick={onClose}>Close</Button>
        <Button onClick={handlePrint}>
          <Printer className="w-4 h-4 mr-2" />
          Print
        </Button>
      </div>
    </div>
  );
}
