'use client';

import { useRef } from 'react';
import { Button } from '@/components/ui';
import { Printer } from 'lucide-react';
import type { Donation } from '@/types';

interface DonationReceiptProps {
  donation: Donation;
  churchName?: string;
  onClose: () => void;
}

function formatCurrency(amount: number): string {
  return `GHS ${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export default function DonationReceipt({ donation, churchName = 'Church', onClose }: DonationReceiptProps) {
  const receiptRef = useRef<HTMLDivElement>(null);

  const donorName = donation.donorId
    ? `${donation.donorId.firstName} ${donation.donorId.lastName}`
    : 'Anonymous';

  const handlePrint = () => {
    const content = receiptRef.current;
    if (!content) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Donation Receipt</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; }
            h1 { font-size: 24px; color: #333; margin-bottom: 4px; }
            .subtitle { color: #666; font-size: 14px; margin-bottom: 32px; }
            table { width: 100%; border-collapse: collapse; margin: 24px 0; }
            td { padding: 10px 0; border-bottom: 1px solid #eee; }
            td:first-child { color: #666; width: 40%; }
            td:last-child { font-weight: 500; }
            .amount { font-size: 18px; }
            .footer { margin-top: 32px; color: #999; font-size: 12px; }
            @media print { body { padding: 20px; } }
          </style>
        </head>
        <body>
          ${content.innerHTML}
          <script>window.print(); window.close();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div>
      <div ref={receiptRef}>
        <h1 style={{ fontSize: '24px', color: '#333', marginBottom: '4px' }}>Donation Receipt</h1>
        <p style={{ color: '#666', fontSize: '14px', marginBottom: '32px' }}>{churchName}</p>

        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <tbody>
            <tr>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Donor</td>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee' }}>{donorName}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Date</td>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee' }}>{formatDate(donation.donationDate)}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Amount</td>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', fontSize: '18px', fontWeight: 'bold' }}>{formatCurrency(donation.amount)}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Type</td>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', textTransform: 'capitalize' }}>{donation.donationType || 'General'}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Payment Method</td>
              <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', textTransform: 'capitalize' }}>{donation.paymentMethod?.replace('_', ' ') || 'N/A'}</td>
            </tr>
            {donation.fundBucketId && (
              <tr>
                <td style={{ padding: '10px 0', borderBottom: '1px solid #eee', color: '#666' }}>Fund</td>
                <td style={{ padding: '10px 0', borderBottom: '1px solid #eee' }}>{donation.fundBucketId.name}</td>
              </tr>
            )}
          </tbody>
        </table>

        <p style={{ color: '#999', fontSize: '12px', marginTop: '32px' }}>
          This receipt was generated by {churchName} via Sanctuary Connect.
        </p>
      </div>

      <div className="flex justify-end gap-3 pt-4 border-t border-border mt-6">
        <Button variant="outline" onClick={onClose}>Close</Button>
        <Button onClick={handlePrint}>
          <Printer className="w-4 h-4 mr-2" />
          Print
        </Button>
      </div>
    </div>
  );
}
